name: Docker Image CI

on:
  push:
    branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        registry: tjsacs.azurecr.io
        username: ${{ secrets.DOCKER_USERNAME2 }}
        password: ${{ secrets.DOCKER_PASSWORD2 }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: tjsacs.azurecr.io/devex-awx-ee
